### ISSUE TITLE
Cronjob not pulling data without the -F flag

### ISSUE THREAD

**Issue by jarrodmast** [campai-bv/autotask-dashboards-os#65]
I had to rebuild my VM that was running the dashboards and since doing so cannot get it to pull all ticket data with the standard (every 5 mins) cronjob command.
I have two cronjobs setup as documented - I'm running the latest commits pulled from 1.5.2 branch.

a standard import routine finds time entries for today, but not any tickets - see log below (logging set to 2).

```
2014-04-04 14:22:24 Cronjob: Starting with the import..
2014-04-04 14:22:44 Cronjob: > Updating all the picklists..
2014-04-04 14:22:48 Cronjob: ..done.
2014-04-04 14:22:48 Cronjob: > Importing completed tickets into the database..
2014-04-04 14:22:49 Cronjob: ..done - nothing saved, query returned no tickets.
2014-04-04 14:22:49 Cronjob: > Importing open tickets into the database..
2014-04-04 14:22:50 Cronjob: ..done - nothing saved, query returned no tickets.
2014-04-04 14:22:50 Cronjob: > Processing the tickets data into totals for all dashboards..
2014-04-04 14:22:50 Cronjob:    > Calculating ticket status totals for all dashboards..
2014-04-04 14:22:53 Cronjob:    ..done.
2014-04-04 14:22:53 Cronjob:    > Calculating total open tickets for all dashboards..
2014-04-04 14:22:53 Cronjob:    ..done.
2014-04-04 14:22:53 Cronjob:    > Calculating kill rate totals for all dashboards..
2014-04-04 14:22:53 Cronjob:    ..done.
2014-04-04 14:22:53 Cronjob:    > Calculating queue health totals for all dashboards..
2014-04-04 14:22:53 Cronjob:    ..done.
2014-04-04 14:22:53 Cronjob:    > Calculating tickets by source for all dashboards..
2014-04-04 14:22:54 Cronjob:    ..done.
2014-04-04 14:22:54 Cronjob:    > Calculating tickets by source for all dashboards..
2014-04-04 14:22:55 Cronjob:    ..done.
2014-04-04 14:22:55 Cronjob: > Importing time entries..
2014-04-04 14:22:55 Cronjob:    > Deleting time entries created 2014-04-04..
2014-04-04 14:22:55 Cronjob:    ..done.
2014-04-04 14:22:55 Cronjob:    > Importing time entries into the database for today (2014-04-04)..
2014-04-04 14:22:59 Cronjob:    ..done - imported 42 time entries.
2014-04-04 14:22:59 Cronjob: ..done.
2014-04-04 14:22:59 Cronjob: > Importing active resources into the database..
2014-04-04 14:23:01 Cronjob: ..done - found 15 active resource(s), saved 0 new ones.
2014-04-04 14:23:01 Cronjob: > Clearing cache for all dashboards..
2014-04-04 14:23:01 Cronjob: ..done.
2014-04-04 14:23:01 Cronjob: Success! Everything imported correctly.
```

i seriously hope i missed something and this isn't my timezone bugging me again!

**Comment by coencoppens** [comment]
@jarrodmast nothing better than a fresh install (if it's working..) ;-)

I don't think it's a timezone issue. I have a couple of dashboards running in different timezones, no weird things yet.

Are there any errors in the error.log? Or any php errors?

**Comment by jarrodmast** [comment]
The cake error log - nothing repeating that lines up with my usual polling of data. These exceptions are from yesterday, nothing for today.

```
2014-04-07 10:34:21 Error: [MissingActionException] Action AppController::index() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'index',
)
Request URL: /app/
Stack Trace:
#0 /var/www/cakephp/lib/Cake/Routing/Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/cakephp/lib/Cake/Routing/Dispatcher.php(162): Dispatcher->_invoke(Object(AppController), Object(CakeRequest), Object(CakeResponse))
#2 /var/www/cakephp/app/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-07 10:37:25 Error: [MissingActionException] Action AppController::Autotask.import_from_autotask() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'Autotask.import_from_autotask',
)
Request URL: /app/Autotask.import_from_autotask
Stack Trace:
#0 /var/www/cakephp/lib/Cake/Routing/Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/cakephp/lib/Cake/Routing/Dispatcher.php(162): Dispatcher->_invoke(Object(AppController), Object(CakeRequest), Object(CakeResponse))
#2 /var/www/cakephp/app/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-07 10:37:29 Error: [MissingControllerException] Controller class Autotask.importFromAutotaskController could not be found.
Exception Attributes: array (
  'class' => 'Autotask.importFromAutotaskController',
  'plugin' => NULL,
)
Request URL: /Autotask.import_from_autotask
Stack Trace:
#0 /var/www/cakephp/app/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
```

no other errors found in apache logs etc ... help?
i've tweaked my cron to run -f mode every 15 which seems to work okay.
its weird that without it still works for time entries, just not tickets?!
