### ISSUE TITLE
Problem with SOAP Request

### ISSUE THREAD

**Issue by digitrance** [campai-bv/autotask-dashboards-os#90]
Hi there,

I have everything up and running in Ubuntu 14.04 LTS. Cake is running and I have no errors from it. The last issue I am having is regarding getting the SOAP request to complete successfully. I run from the command prompt to test:

```
$ sudo sh /var/www/html/lib/Cake/Console/cake -app /var/www/html/app Autotask.import_from_autotask

Welcome to CakePHP v2.5.5 Console
---------------------------------------------------------------
App : app
Path: /var/www/html/app/
---------------------------------------------------------------
Error: Internal Server Error
#0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'https://webserv...', 'http://autotask...', 1, 0)
#1 /var/www/html/app/Plugin/Autotask/Model/Behavior/AutotaskBehavior.php(80): SoapClient->__call('query', Array)
#2 /var/www/html/app/Plugin/Autotask/Model/Behavior/AutotaskBehavior.php(80): SoapClient->query(Array)
#3 [internal function]: AutotaskBehavior->queryAutotask(Object(Ticket), 'Ticket', Array)
#4 /var/www/html/lib/Cake/Model/BehaviorCollection.php(239): call_user_func_array(Array, Array)
#5 /var/www/html/lib/Cake/Model/Model.php(803): BehaviorCollection->dispatchMethod(Object(Ticket), 'queryAutotask', Array)
#6 /var/www/html/app/Plugin/Autotask/Model/Ticket.php(282): Model->__call('queryAutotask', Array)
#7 /var/www/html/app/Plugin/Autotask/Model/Ticket.php(282): Ticket->queryAutotask('Ticket', Array)
#8 /var/www/html/app/Plugin/Autotask/Model/Ticket.php(48): Ticket->_findClosedInAutotask(Array)
#9 /var/www/html/app/Plugin/Autotask/Console/Command/Task/GetTicketsCompletedTodayTask.php(38): Ticket->findInAutotask('closed', Array)
#10 /var/www/html/app/Plugin/Autotask/Console/Command/ImportFromAutotaskShell.php(41): GetTicketsCompletedTodayTask->execute()
#11 /var/www/html/lib/Cake/Console/Shell.php(440): ImportFromAutotaskShell->main()
#12 /var/www/html/lib/Cake/Console/ShellDispatcher.php(209): Shell->runCommand(NULL, Array)
#13 /var/www/html/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#14 /var/www/html/lib/Cake/Console/cake.php(54): ShellDispatcher::run(Array)
#15 {main}
```

I have checked and double-checked that I am pulling from the correct Autotask server.

It appears I am making a successful SOAP request as I have data in a file in /tmp/wsdl-root-####

I also have a good database connection and the correct credentials configured for Cake, but the data never makes it to the database.

It looks like /Autotask/Console/Command/ImportFromAutotaskShell.php should be logging what it's doing to a cronjob log, but when I check /var/log/syslog there is no relevant information.

Where can I go to check to see where this is failing?

Thanks....

**Comment by coencoppens** [comment]
I've seen this before when an incorrect Autotask Server was being used. If I have to guess, you're using an American server (probably webservices3?). Can you give it a try with webservices1?

**Comment by digitrance** [comment]
Thanks for the reply! I was using webservices5, as our Autotask runs through ww5.autotask.net. I tried changing to webservices1 and am still getting the same Internal Server Error.

**Comment by jrdnr** [comment]
Same issue here, our normal connection url is ww3.autotask.net so I was trying webservices3, Also tried webservices1 as @coencoppens suggested previously.  Was this issue ever resolved? I'm guessing this must be an issue in my config as the issue is this old and still 'Unresolved'.  However I've been over the config instructions and cannot find any issues.

```
Welcome to CakePHP v2.3.4 Console
---------------------------------------------------------------
App : app
Path: /var/www/app/
---------------------------------------------------------------
Error: Internal Server Error
#0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'https://webserv...', 'http://autotask...', 1, 0)
#1 /var/www/app/Plugin/Autotask/Model/Behavior/AutotaskBehavior.php(236): SoapClient->__call('getThresholdAnd...', Array)
#2 /var/www/app/Plugin/Autotask/Model/Behavior/AutotaskBehavior.php(236): SoapClient->getThresholdAndUsageInfo()
#3 /var/www/app/Plugin/Autotask/Model/Behavior/AutotaskBehavior.php(273): AutotaskBehavior->checkConnectAutotask()
#4 [internal function]: AutotaskBehavior->connectAutotask(Object(Ticket))
#5 /var/www/lib/Cake/Model/BehaviorCollection.php(244): call_user_func_array(Array, Array)
#6 /var/www/lib/Cake/Model/Model.php(796): BehaviorCollection->dispatchMethod(Object(Ticket), 'connectAutotask', Array)
#7 /var/www/app/Plugin/Autotask/Console/Command/ImportFromAutotaskShell.php(96): Model->__call('connectAutotask', Array)
#8 /var/www/app/Plugin/Autotask/Console/Command/ImportFromAutotaskShell.php(96): Ticket->connectAutotask()
#9 /var/www/lib/Cake/Console/Shell.php(392): ImportFromAutotaskShell->main()
#10 /var/www/lib/Cake/Console/ShellDispatcher.php(200): Shell->runCommand('-f', Array)
#11 /var/www/lib/Cake/Console/ShellDispatcher.php(68): ShellDispatcher->dispatch()
#12 /var/www/lib/Cake/Console/cake.php(50): ShellDispatcher::run(Array)
#13 {main}
```
